### ISSUE TITLE
Gantt dependances

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#1]
Il faut faire l'ajout des taches et tout et tout

**Comment by squelletton** [comment]
Liste de choses à faire pour y répondre
- [ ] Affichage du "+" sur la partie libre
- [ ] cliquer sur le "+" pour obtenir une flèche qui suit le curseur
- [ ] lier la flèche à une autre tache
- [ ] un affichage de la flèche qui entrave/gène le moins possible les autres taches - en lien avec #4 
- [ ] une fois la dépendance crée, laissé possible l'ajout de lien avec un nouveau "+"

**Comment by Zetrypio** [comment]
J'avais pas pensé à faire un +.
**Le problème du +, c'est que :**
 - Si cette tâche à déjà une flèche, il y a plus de + (ou alors c'est embrouillé car tout se superpose - d'après ce que j'ai compris). 
 - Tu es obligé de faire la flèche toujours dans le même sens.

**Du coup, j'avais plutôt pensé, à faire :** Clic droit sur la tâche, puis: 
 - Ajouter une dépendance (à cette tâche)
 - Faire de cette tâche une dépendance (pour une autre)

 - On peut éventuellement mettre supprimer / modifier etc.
 - _Ou alors, **au lieu de faire 2 choix**_ (avant une tâche ? vs. après une tâche ?) on peut dire :
"Ajouter une relation de dépendance" -> Cela permet de choisir _n'importe quelle autre tâche._ Si l'autre est avant : c'est que celle-ci en dépend de cette autre, sinon c'est le contraire.
 - Voire, on peut même mettre tout ça ET un + ! (même si le + ne serais pas tout le temps présent - car il disparaîtrait sous les flèches...).

**Comment by squelletton** [comment]
j'avais pensé au "+" qui passe en dessous de la flèche 

> Ou alors, au lieu de faire 2 choix (avant une tâche ? vs. après une tâche ?) on peut dire :
"Ajouter une relation de dépendance" -> Cela permet de choisir n'importe quelle autre tâche. Si l'autre est avant : c'est que celle-ci en dépend de cette autre, sinon c'est le contraire.
ça me parait pas mal.

> Voire, on peut même mettre tout ça ET un + ! (même si le + ne serais pas tout le temps présent - car il disparaîtrait sous les flèches...).
Donc on peut faire ça, mais il faut se mettre au point sur l'affichage, si on fait une flèche qui prend une case ou qqch de plus soft qui permettrait de mettre des taches desus

**Comment by squelletton** [comment]
"+" à afficher seulement quand il n'y a pas encore de lien qui commence par la tache en question
