### ISSUE TITLE
Pouvoir dissocier une tache à répétition des autres

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#102]
Ce serait sympa de pouvoir "retirer" de la liste des taches à répétitions pour la supprimer ou la décaler.
Exemple :
 - Manger 
     - tache répétable
     - quotidienne 
     - à 12h
     - pendant une semaine

Et un jour on va faire une activié à 12h, donc manger doit se déplacer ce jour précis et pas les autres.

**Comment by Zetrypio** [comment]
Incroyable ! Il est de retour ! Pour nous jouer des mauvais tours ! =)

Plus sérieusement, il faudrait pour faire cela considérer la tâche comme une tâche conteneur OU comme un groupe.
Ou alors, gérer un système d'*exception* de tâche, par exception je n'entend pas les erreurs créés par un `raise` ou autre, mais plutôt une liste des cas particuliers à gérer différemment pour les tâches, avec les modifications nécéssaires (suppression possiblement comprise).

**Comment by squelletton** [comment]
A vrai dire je pensais faire une liste d'exception, où la liste contiendrais les taches à ne pas répéter.
De plus lors de la "dissociation" de la tache, on crée une nouvelle tache copie de la tache à répétition avec seulement une répétition et placé le bon jour.

Faire d'une tache à répétition une tache conteneur peut rapidement devenir illisible pour le Treeview, de même pour le groupe, et en appliquant un groupe à une tache à répétition cela peut compliquer certaines choses.

Je suis d'accord qu'il n'est pas certains que faire une liste d'exception soit la meilleure option, néanmoins cela reste une bonne option.

**Comment by Zetrypio** [comment]
Je suis pour la liste d'exception, je l'avais pensé plus compliqué donc c'est bien que tu ai trouvé une méthode plus simple =).
Je pense que faire une liste d'exception + recréer une *sous*-tâche peut-être pas mal. (Ça permettrait dans le `Treeview` d'afficher les exceptions de *tâches modifiées* (pas supprimés) dans une sous-partie de l'arborescence `Treeview`, ce serait pas mal ? Désolé si je recomplique encore les choses, j'ai pas les pensées simples... Surtout que si on appuie sur __dissocier__, on s'attend à voir une nouvelle tâche apparaître donc ta technique est certainement meilleure. De plus, si tu as déjà commencé à faire quelque chose, je ne voudrais pas t'embrouiller dans ce que tu fais / ce que tu as déjà fait.)

**Comment by squelletton** [comment]
J'ai encore rien fait, (je m'attaque aux statut "Inconnu" des taches conteneurs, je remplace par un compteur de taches faites)

J'avais pas pensé rajouté une ligne d'exception dans la tache à répétition du `Treeview`.
Seulement garder la tache à répétition de x jours + dupliquer la tache.
Si à l'origine cette tache est en format D&D ça permet de rajouter une subtask.
Je vais voir si j'ai le temps d'attaquer ça, au pire on pourra revenir dessus si jamais mafaçon te parait bizarre

**Comment by Zetrypio** [comment]
> (je m'attaque aux statut "Inconnu" des taches conteneurs, je remplace par un compteur de taches faites)

Que signifie cette phrase ?
Il faut que tu fasse attention à garder ce getter de statut, qui est utilisé à plusieurs endroits
(tri de l'arbre, affichage dans la zone statut de l'arbre etc.)

**Comment by Zetrypio** [comment]
(Aussi, n'oublie pas de t'assigner à l'issue *si tu veux la faire*.)

**Comment by squelletton** [comment]
J'ai pas trop bien compris pour les filtres, ce que j'ai fais, c'est juste modifier le `getHeader` de l'interface dans `Task`de façon à ce que ça renvoie un texte joli.
J'ai essayé de toucher au reste mais ça marchait pas trop bien, au final seul le texte du `Treeview` est changé, le statut reste `"Inconnu"`

```py
def getHeader(self):
        """
        Permet de donner la ligne d'entête de cet objet dans l'affichage du Treeview() du TaskEditor().
        Affiche le nombre de taches faites si c'est une tache conteneur
        @return Le nom suivi du statut
        @specified by getHeader() in ITaskEditorDisplayableObject().
        """
        return self.getNom(), self._statut
        return self.getNom(), self._statut if self._statut != "Inconnu" else str(len(["a" for subT in self.getSubTasks() if subT.isDone()])) + "/" + str(len(self.getSubTasks()))
```
