### ISSUE TITLE
La sélection des tâche n'est pas toujours identique entre le Treeview et l'affichage.

### ISSUE THREAD

**Issue by Zetrypio** [Zetrypio/TaskManager#103]
## La sélection des tâches n'est pas toujours identique entre le `Treeview` et l'affichage.
C'est ce qui reste à faire pour la sélection des tâches au `Treeview` comme indiqué dans #54.

### Voici ce qu'il faut faire :
 - **Gestion de la multi-sélection dans le `Treeview` :**
   - [x] multi-sélection dans le `Treeview` possible
   - [x] Contrôle-clic dans le `Treeview` pour multi-sélection, mais simple clic reste une sélection simple.
     - [x] **Ce n'est plus le cas !** (*à reformuler alors*) : Cependant, un contrôle-clic ne permet de sélectionner que les tâches, donc un contrôle-clic engendrera de sélectionner les lignes parentes correspondant aux objets planifiables à toutes lignes auparavant sélectionnés, pour être conforme au troisième effet secondaire (en gros : multi-sélection possible seulement sur les lignes correspondant aux objets planifiables.).
 - **Détection correcte des tâches (et autre objets planifiables) :**
 __Cela signifie :__ "sélectionner quelque chose quelque part sélectionne *la même chose* ailleurs".
   - [x] détection correcte de la sélection des tâches de l'affichage pour sélectionner dans le `Treeview`
   - [x] détection correcte de la sélection des tâches du `Treeview` pour sélectionner dans l'affichage
 - **Dé-sélections correctes :**
   - [x] dé-sélection du `Treeview` implique dé-sélection de l'affichage.
   - [x] dé-sélection de l'affichage implique dé-sélection du `Treeview`.
### Attention aux effets secondaires :
   - [x] La sélection dans le `Treeview` ne doit pas gêner le Drag&Drop, comme ce fût le cas précédemment.
     - [x] En particulier, il ne doit pas être possible de Drag&Drop plusieurs tâches en même temps.
   - [x] La sélection d'un groupe entier ou d'une tâche conteneur n'est pas égale à la sélection de ses composantes.
Il faut donc adapter la sélection ***dans les 2 sens*** en conséquence.
Il s'agit seulement que *l'englobante implique l'englobée*, c'est-à-dire qu'une action (sélection ou dé-sélection) sur le groupe où la tâche conteneur répercute la même action sur les sous-tâches, mais pas plus.
   - [x] Il existe des lignes du `Treeview` qui ne correspondent pas à des objets planifiables, et qui quand sélectionnées *ne doivent pas interférer avec l'affichage*, mais **il doit rester possible de pouvoir les sélectionner si besoin** (par exemple, déplacement clavier sur le `Treeview` du `TaskEditor`...
   - [x] Cela doit aussi fonctionner avec l'affichage avec les périodes.

**Comment by squelletton** [comment]
J'avais fait un truc "rapide" ça marche à peu près.
Pour la multisélection dans un Treeview je crois qu'il y a quelques mesures à prendre.

**Comment by Zetrypio** [comment]
Je m'en occupe de toutes façon

**Comment by squelletton** [comment]
Il y a un bug losrqu'on copie colle une tache (de n'importe quel type). La selection est HS après avec une erreur dans la console (je te laisse regarder).
