### ISSUE TITLE
Duplication  des taches via DnD

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#14]
C'est surement fait exprès mais je propose une amélioration.
Dans le Treeview, au lieu d'avoir :
![image](https://user-images.githubusercontent.com/63096846/78468821-8d7fb280-771b-11ea-9b5a-e2962c258163.png)
Avec un "Inconnu" et 2 "à faire"
Pourquoi ne pas remplacer par 
- Inconnu -> fait/à faire (tant qu'il y en un de tous qui n'est pas fait)
  - à faire
  - à faire

En gros mettre la tache global qu'on a créer en parent et la tache a faire en enfant. Tu as compris ?

**Comment by Zetrypio** [comment]
oui j'ai compris
