### ISSUE TITLE
DnD ne fonctionne pas sur les taches déjà planifée

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#15]
Quand on planifie une tache manuellement, on ne peux pas la grab pour la dupliquer depuis le treeview

**Comment by Zetrypio** [comment]
Il me semblait que c'était ce qui était prévu de base.
On peut au pire faire dans le RMenu une option pour "dupliquer en tant qu'inconnu" et ensuite on pourra Drag & Drop. L'inconnu sera comme dans #14 , c'est-à-dire en tant que tâche parente.
