### ISSUE TITLE
[Calendrier_et_périodes] Créer les boutons présents dans la barre d'outils des périodes

### ISSUE THREAD

**Issue by Zetrypio** [Zetrypio/TaskManager#17]
Voici les boutons présents dans la barre d'outils des périodes, celle qui est présente lorsqu'on clique sur l'onglet pour Gérer les Périodes.

Il doit y avoir :
 - Gestion des périodes :
   - [x] Déplacer
   - [x] Dupliquer
   - [x] Supprimer
   - [x] Sélectionner
 - Division des périodes :
   - [x] Scinder
   - [x] Fusionner
 - Tâches indépendantes :
   - [x] Lier à une période
   - [x] Dupliquer
   - [x] Supprimer

**Comment by squelletton** [comment]
Je te propose dans gestion des période
- Scinder -> coupe une période en 2
- modifier (pour rentrer dans le mode édition d'une simple période ?)

**Comment by Zetrypio** [comment]
Apparemment, le Fixes #17 doit se mettre à la fin du nom d'un commit (même pas de points après)

**Comment by Zetrypio** [comment]
je suppose
