### ISSUE TITLE
[Dépendance] Pouvoir supprimer un lien en cliquant dessus

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#34]
- [x] Idée 1 :
 - On clic sur supprimer un lien depuis une tache
 - on clique sur le lien que l'on veux supprimer
 - et hop c'est fait sans devoir cliquer sur la tache à l'autre bout du lien

 - [x] Idée 2 : 
 - On clique sur le lien
 - Semblant de sélection du lien
 - bind de la touche suppr
 - [x] Idée 3 : variante avec un clique droit -> retirer le lien

Les deux idée ne sont pas incompatible, tu en pense quoi ?

**Comment by Zetrypio** [comment]
Les 3 idées sont possibles

**Comment by squelletton** [comment]
Manque plus que la dernière idée
