### ISSUE TITLE
[Big Calendrier] Les textures de la barre d'outil

### ISSUE THREAD

**Issue by Zetrypio** [Zetrypio/TaskManager#38]
Voici les boutons présents dans la barre d'outils des périodes, celle qui est présente lorsqu'on clique sur l'onglet pour Gérer les Périodes.

Il faut créer les textures pour les boutons présents dans #17 .
Il doit y avoir :
 - Gestion des périodes :
   - [x] **Déplacer :** Permet de déplacer la ou les périodes sélectionnés.
   - [x] **Dupliquer :** Permet de dupliquer la période sélectionnée (1 seule), en la reconfigurant.
   - [x] **Supprimer :** Permet de supprimer la ou les périodes sélectionnées (marche aussi avec suppr ou clic droit ?).
 - Division des périodes :
   - [x] **Scinder :** Permet de découper  la période sélectionnée (1 seule) en 2 à un moment choisi.
   - [x] **Fusionner :** Permet de rejoindre toutes les périodes sélectionnées, du début de la première à la fin de la dernière.
 - Tâches indépendantes :
   - [x] **Lier à une période :** Permet de lier la tâche à une période pour qu'elle ne soi plus indépendante.
   - [x] **Voir dans une autre vue :** Ouvre une fenêtre demandant dans quelle vue on veut voir la tâche. Cela la sélectionne aussi dans la vue en question.
   - [x] **Supprimer :** Permet de supprimer la tâche indépendante.

**Comment by squelletton** [comment]
Pour moi, je pense qu'il me serait préférable de rassembler tout ce qui est texture là -> #8 
A mettre sur 1 post et réédité à chaque changement de bouton

**Comment by Zetrypio** [comment]
Il vaut mieux une issue pour chaque chose

**Comment by squelletton** [comment]
Oui mais comme c'est des textures, c'est plus simple pour moi de tout faire en même temps avec une unique progress bar (le nombre de cases coché fait une progress bar assez cool)
Je vais peut être même faire un projet (pour voir aussi comment ça fonctionne

**Comment by squelletton** [comment]
Enfaite avec les projets, c'est mieux comme ça.

**Comment by squelletton** [comment]
**Voir dans une autre vue**
![image](https://user-images.githubusercontent.com/63096846/80281655-fd76cc80-870c-11ea-8208-b949fe650d27.png)
![image](https://user-images.githubusercontent.com/63096846/80281669-17b0aa80-870d-11ea-8f57-ebab0b14c221.png)

Voilà ça fait un peut un "sélectionner un jour a zoomer" (je sais pas faire une tache en 4x4 pixel) mais je me dis que c'est pas trop grave car c'est le fond de ta fonction, j'imagine que tu vas vouloir changer le tout, c'est pour ça que je serais dispo ce soir (ou plus tot sur discord).
Voilà la textures
![image](https://user-images.githubusercontent.com/63096846/80281717-70804300-870d-11ea-86f2-5c46c8d9f44e.png)

**Comment by Zetrypio** [comment]
C'est pas mal, j'ai une petite idée, je m'en occuperais si j'ai le temps.

**Comment by squelletton** [comment]
En attente de merge avec principal pour avoir les lignes de codes concernant importPIL et infobulle
