### ISSUE TITLE
Paramétrage des heures

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#40]
Lors du choix de l'heure, si on choisit l'heure avec des chiffres manuellement (num pad ou sur la barre au dessus des lettres) et bien ça fait n'importe quoi =)

**Comment by Zetrypio** [comment]
En réalité, ça ne fait pas n'importe quoi. Comme on écrit un nombre plus grand que 23 pour les heures, ça fait un modulo du nombre par 24. Le résultat est donc très prévisible. Mais que vaudrait-il mieux faire alors ? Ou bien on bloque l'heure sur 23h59, ou bien on annule l'écriture, ou bien on laisse comme c'est.
