### ISSUE TITLE
Bug d'affichage des liens lors de 2 tâches dans 2 jours consécutifs

### ISSUE THREAD

**Issue by Zetrypio** [Zetrypio/TaskManager#46]
Lorsqu’on a deux tâches qui sont dans deux jours consécutifs, si on fait un lien entre les deux, le lien ne s'affiche pas comme il faut. Exemples sur l'image

![image](https://user-images.githubusercontent.com/61354872/79687585-9c508400-8248-11ea-9f70-44cb764c5b22.png)

Il faudrait faire simplement un sinus qui va de la tâche A à la tâche H (ou G à B) dans ce genre de situations.

**Comment by squelletton** [comment]
je vois le problème
