### ISSUE TITLE
Suppression d'une tache

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#53]
Je sais pas si c'est déjà possible, mais ce serais cool
D'autant plus que la sélection est faite reste plus qu'a bind la suppression.

**Edit by Zetrypio :**
 - **Façons de supprimer :**
   - [x] Sélectionner tâche(s) dans l'affichage -> clic droit -> supprimer
   - [x] Sélectionner tâche(s) dans l'affichage -> suppr (touche du clavier)
   - [x] Sélectionner tâche dans Treeview -> clic-droit (#62) -> supprimer
   - [x] Sélectionner tâche dans Treeview -> suppr (touche du clavier)
 - **De plus, Affiche-t-on la confirmation de suppression :**
   - [ ] Jamais
   - [x] Quand on a plus d'un tâche
   - [ ] Toujours
   - [x] On verra pour faire une configuration
(tu as le droit de changer si tu préfère...)

**Comment by squelletton** [comment]
j'ai cocher tout, je sais pas c'est si ce qu'il fallait faire mais pour les façons de supprimer ça me parait bien.

Je vois que tu propose un panneau de configuration J’APPROUVE à 100%. issue sur les trucs à mettre dedans
Pour le clique droit des taches aussi c'est une bonne idée que j'avais eu et que je vais développer en issue pour faire une liste de commandes à mettre dessus.

**Comment by Zetrypio** [comment]
Alors les 4 premières cases, c'est pour la progression de l'avancement de la résolution de l'issue.

**Comment by Zetrypio** [comment]
et pour le panneau, go faire un projet.

**Comment by squelletton** [comment]
Ok je m'en occupe ce soir.

**Comment by Zetrypio** [comment]
Bah en fait cette issue elle est résolue depuis un petit bout de temps en faite...
On ne s'en était pas rendu compte...
