### ISSUE TITLE
Couleur de sélection des taches dans le treeview 

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#54]
J'ai crée un nouvel attribut dans la classe `Task` qui est `currentColor` qui me sert pour changer la couleur des taches sans perdre celle d'origine.

Le truc qui serait bien c'est que ça change aussi dans le Treeview ou au moins sur la ligne principale.
Pour la couleur, j'ai mis le bleu Windows, mais on peut facilement trouver un bleu plus clair et joli enfin ça reste lisible. 
Si on change le type de bleu il faudrait aussi changer celui des liens peut-être pour avoir une sélection monochrome...

**Comment by Zetrypio** [comment]
Pour le coup, dans le Treeview, il vaudrait mieux ne pas changer la couleur, mais faire une sélection de la ligne d'entête. C'est beaucoup mieux car
1. On change pas la couleur
2. On sélectionne réellement la tâche dans le Treeview.
De plus, après le refactoring, il ne s'agit plus de ces 2 attributs, mais des 2 méthodes `getNativeColor()` pour la couleur de base, et `getDisplayColor()` pour la couleur éventuellement sélectionnée.

**Comment by Zetrypio** [comment]
Il faudrait activer la sélection multiple sur le `Treeview` du `TaskEditor`.
Car sinon c'est déjà *à peu près* en place, juste vérifier cette sélection multiple et vérifier que cela fonctionne correctement.

**Comment by Zetrypio** [comment]
ça fonctionne en fait
