### ISSUE TITLE
Mauvais message de warning ou mauvais calcul de quand on doit mettre ce warning.

### ISSUE THREAD

**Issue by Zetrypio** [Zetrypio/TaskManager#55]
Quand on fait 2 périodes comme ceci:
![image](https://user-images.githubusercontent.com/61354872/81099554-63cccd80-8f0b-11ea-891f-30c35f928b5f.png)
Et qu'on fusionne, il y a le message de warning qui dit que 1 ou plusieurs jours ne sont pas dans la période. Voici le message en question pour rappel :
![image](https://user-images.githubusercontent.com/61354872/81099577-71825300-8f0b-11ea-806d-269a95b33d27.png)
Or, Ce n'est pas le cas, c'est juste que les périodes ne se croisent pas. Que faire ?
 - [ ] Faire une vraie détection pour correspondre au message
 - [ ] Changer le message pour que ça corresponde à la situation.
 - [x] Supprimer le warning, car franchement, qu'est-ce qu'on en a à faire ?

**Comment by squelletton** [comment]
Faire la vraie détection n'apporterais pas un bénéfice notable je trouve, si c'est juste pour ça^^
Changer le message, pas besoin
Supprimer le warning -> on ne se fera plus harcelé par le son windows un peu de repos pour nos oreilles

Après supprimer le warning dans ce cas précis me parait normal, si tu souhaite garder le warning quand il y a vraiment 1 (ou plus) jour de vide, ok c'est compréhensif, mais c'est pas urgent, enfin je trouve.

**Comment by Zetrypio** [comment]
On l'enlève.
