### ISSUE TITLE
Comment éditer les taches dans le treeview

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#6]
On peut faire de plusieurs façon à vrai dire et il faudrait se mettre au point, j'en vois 3

 - Bouton "Modifier"
 - "R-menu"
 - Fenêtre d'édition total

**Bouton Modifier**
Placement : où veux tu le mettre
Action : il fait quoi exactement ?

**"R-menu"**
Soit R-clique avec une option pour chacune des attribut à changer
Soit R-clique avec "modifier" qui fait apparaître la fenêtre d'édition total

**Fenêtre d'édition total**
Nouvelle fenêtre avec une liste de tous les attributs et d'un champs pour les éditer
Placement : Bouton ou R-menu ou autre ?

**Comment by Zetrypio** [comment]
J'avais pensé à soit :
 - **Bouton** en haut avec :
   - Modifier (fenêtre d'édition de la tâche sélectionnée)
   - Supprimer (la tâche sélectionnée)
 - **RMenu** avec :
   - Modifier (fenêtre d'édition de la tâche sélectionnée)
   - Supprimer (la tâche sélectionnée)

**Comment by squelletton** [comment]
Moi j'ai une préférence pour le R-Menu, histoire de ne pas avoir une surcharge de bouton

**Comment by Zetrypio** [comment]
Donc on fait le RMenu, j'ai importé la classe.
