### ISSUE TITLE
RMenu sur les taches

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#63]
Liste de commande disponibles sur le RMenu qu'on obtient via une tache : 
- [x] Supprimer
- [ ] Sélectionner le groupe (si jamais il y en a un) (Edit by Zetrypio : Impossible dans le Treeview du TaskEditor() car les tâches sont déjà affiché sous le groupe, et dans l'affichage aussi donc c'est non.)

Voilà si tu as d'autres idées n'hésite pas.
Il y a sûrement une façon de faire pour séparer le RMenu de Gantt et des autres calendriers (pour les liens). faudra pas oublier de traiter ça.

On reporte le même RMenu sur le treeview ?

**Comment by Zetrypio** [comment]
C'est bon
