### ISSUE TITLE
colonnes buguées

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#73]
![image](https://user-images.githubusercontent.com/63096846/87169373-2c461d00-c2d0-11ea-81c6-980d0626db86.png)
Comment faire :
- Avoir 2 taches en même temps
- Créer 1 troisième tache en même temps

Le dérèglement des colonnes donne aussi : 
![image](https://user-images.githubusercontent.com/63096846/87169297-0f114e80-c2d0-11ea-83b4-b05e4f725582.png)

**Comment by Zetrypio** [comment]
Possiblement duplicate of #72
