### ISSUE TITLE
l'horloge et les heures

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#79]
![image](https://user-images.githubusercontent.com/63096846/87855439-a6058880-c918-11ea-8bbb-c785720c4ec0.png)
J'ai changé le système d'envoie car j'ai changé data.
Au lieu d'envoyer `"number"` en string j'envoie direct un bool car de toute façon tu faisais pour crée l'horloge `"number"==style`
Mais ça marche pas..., enfin le bool est passé mais la condition s'execute tous les 10 lancements alors bon...

**Comment by Zetrypio** [comment]
Comme montré dans cette image, ce n'est pas un `bool`, mais un `str`.
![image](https://user-images.githubusercontent.com/61354872/89039680-ca169000-d342-11ea-9f63-adead2de34ac.png)

J'ai fait une correction.
