### ISSUE TITLE
Les textures

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#8]
Travaille @Maliochka !
Les textures doivent-être intuitive car on supprime le texte

- [x] Ajouter
   - [x] **Heure** à la liste (avant/après)
   - [x] **Jour** à la période (avant/après)
- [x] Groupe
   - [x] **Grouper** permet de rassembler des taches
   - [x] **Dégrouper** permet de séparer les taches sélectionnés
- [x] Retirer
   - [x] **Heure** à la liste (avant/après) et combien
   - [x] **Jour** à la liste (avant/après) et combien
 - [x] Vue
   - [x] **Sélectionner un jour** permet de déplacer le jourDebut rapidement
   - [x] **Afficher/Masquer**  ouvre une fenêtre qui choisit les tache à afficher sur une période
 - [x] Déplacer
   - [x] **Intervertir** les activité d'un jour avec un autre (remplacer jeudi par samedi)
   - [x] **X activité de Y jours** similaire à la précédente sans changer toutes les activité
   - [x] **X activité de Y heures** peut être combiné avec la précedente
 - [x] Avancement
   - [x] **Validation** Valide les taches sélectionné
   - [x] **Jour fini** Toutes les activités de today.now sont coché comme validé
   - [x] **Normal** Similaire à la précédente en prenant en compte les heures aussi

**Comment by squelletton** [comment]
Il faut que je fasse quelle taille, pour quelle ne soit pas trop grosse et qu'on ai une sorte de modèle ?

**Comment by Zetrypio** [comment]
- Pour les grands boutons : 48x48
 - Pour les petits boutons (ceux qui ont plusieurs lignes dans leurs cases) : 19x19

**Comment by squelletton** [comment]
J'ai un peu changer les boutons, j'ai combiné déplacer et décaler

**Comment by Zetrypio** [comment]
De même que dans #7 ,
Peux-tu rajouter une description sur chacun de tes boutons dans ton issue (mettre le nom en gras et la description en normal après) stp ?

Et pour l'image du bouton, on pourra éventuellement mettre un petit texte (dans l'image) quand même. Comme ça on pourra avoir l'impression qu'il y a une image et un bouton.

Format d'image requise / possibles : gif ou bmp ou jpg ou mieux : **PNG**.
Cependant, si on utilise bmp, jpg ou png, il faut installer PIL.
Je peux m'occuper d'un auto-installer.

**Comment by squelletton** [comment]
taille 
hauteur = 48
longueur max = 48*3 = 144

**Comment by Zetrypio** [comment]
pour les petits bouton:
hauteur = 19
largeur : entre 19 et 19x5 = 95

**Comment by squelletton** [comment]
Premier shooting photo
**Ajout Heure**
![image](https://user-images.githubusercontent.com/63096846/79689033-8f389280-8252-11ea-9240-8a34692af900.png)
![image](https://user-images.githubusercontent.com/63096846/79689053-aa0b0700-8252-11ea-8810-5965ccf0c8da.png)
Le texte heure me semble un peu en dessus du plus, qu'en penses tu ? (il est centré sur un plus 'pair' donc ici il est pixel-dessus en gros, la barre du H fait 2 pixels celle du haut est totalement noir et celle du dessous est un peu transparente, j'ai fixé celle toute noir en haut donc c'est centré mais un peu haut, ça se voit beaucoup.

**Retirer Heure**
![image](https://user-images.githubusercontent.com/63096846/79689854-be053780-8257-11ea-9107-db6f2fa8060e.png)
![image](https://user-images.githubusercontent.com/63096846/79689899-07ee1d80-8258-11ea-852f-c7e18c904cda.png)
J'ai fais une croix car un moins rend moche, dis moi si ça te va. D'un coté ça fait un peu "annuler"

**Retirer Jour**
![image](https://user-images.githubusercontent.com/63096846/79690455-c317b600-825a-11ea-9fe2-53cc7485f16c.png)
![image](https://user-images.githubusercontent.com/63096846/79690462-cad75a80-825a-11ea-98c0-ba2ca6b67050.png)
Voilà même délire avec les jours

Coche les images que tu valides sur la liste en haut

**Comment by squelletton** [comment]
Troisème shooting photo

**Vue**
![image](https://user-images.githubusercontent.com/63096846/79775723-f3cc1e00-8334-11ea-8ad0-146770aa9aaf.png)
![image](https://user-images.githubusercontent.com/63096846/79775739-faf32c00-8334-11ea-98a4-a583214779d5.png)
ça me parait un peu petit, et 'avais pas trop d'idée, mais ça rend sympa, dis moi si tu aimes bien.
Je sais pas si ça exprime bien le sélectionner un jour à voir

**Comment by Zetrypio** [comment]
Pour retirer, je pense qu'il vaudrait mieux mettre un `-` en rouge, c'est plus logique, non ?

**Comment by Zetrypio** [comment]
Tu pourrais mettre les images dans les bons boutons comme ca on a une idée de ce qui se passe, de manière plus globale ?

**Comment by Zetrypio** [comment]
et pour le afficher / masquer, je pense à un truc du genre :
![image](https://user-images.githubusercontent.com/61354872/79903263-0d439780-8413-11ea-91ef-1ed6f9207021.png)
(oui bon je sais c'est moche et c'est pas droit et tout et tout)

**Comment by squelletton** [comment]
> Pour retirer, je pense qu'il vaudrait mieux mettre un `-` en rouge, c'est plus logique, non ?

ça fait un peu "tiret" je te fais un visuel dans l'aprem pour que tu vois


> Tu pourrais mettre les images dans les bons boutons comme ca on a une idée de ce qui se passe, de manière plus globale ?

Eh bien dans la théorie oui, seulement, enfaite la texture a charger s'appelle test.png et enfaite j'utilise toujours la même, ce qui m'évite de changer le code à chaque fois, dans la pratique je ne touche jamais au code, je la charge une fois pour qu'on ai une idée de ce que ça donne dans un bouton maintenant, je place pas à chaque fois car ça m'arrive de faire une texture d'essayer puis de revenir sur une autre pour tester un truc et revenir en arrière, bref ça me facilite la vie.
Tu veux vraiment que je les places bien pour les valider ?





> et pour le afficher / masquer, je pense à un truc du genre :

moi aussi avec un oeil et un oeil barré, et j'hésitais, est-ce que je fais 2 textures : 
- en mode désactive
- en mode activé (pour savoir si on voit tout ou pas)

Ou alors on met un texte à coté type active ou une infobulle qui indique l'état (infobulle/texte ça doit être moins lourd à charger)

Je conclue que tu ne valide pas "sélectionner jour" ou tu attends que je le présente à ça place (je te renvoie à mon pavé ci-dessus) ?

**Comment by squelletton** [comment]
**Afficher/masquer**
inspirée ton idée
![image](https://user-images.githubusercontent.com/63096846/79987825-2c433780-84ae-11ea-9c6a-433d8b4d0edf.png)
![image](https://user-images.githubusercontent.com/63096846/79987847-32391880-84ae-11ea-9555-32016178f61f.png)
Dis moi si tu trouve l'imperfection de la texture (si tu la trouve c'est que ça se voit et on change)
Mais comment on fait pour savoir s'il y a un filtrage actif ou pas ?

Ce que j'avais en tête
![image](https://user-images.githubusercontent.com/63096846/79990518-6feb7080-84b1-11ea-963f-4e9e26aa494f.png)
![image](https://user-images.githubusercontent.com/63096846/79990563-7f6ab980-84b1-11ea-8c0b-395e80c8d3f7.png)
A droite la version où certaines taches sont masquées et à gauche - aucun filtre actif

**Intervertir**
![image](https://user-images.githubusercontent.com/63096846/79995977-35390680-84b8-11ea-9e09-519144d4bc08.png)
![image](https://user-images.githubusercontent.com/63096846/79996014-3b2ee780-84b8-11ea-8510-be3de6f5b996.png)
J'ai eu du mal à trouver un truc lisible, t'arrive à voir le bout des flèches ?

**Retard**
![image](https://user-images.githubusercontent.com/63096846/79997509-f86e0f00-84b9-11ea-9598-0d406f60631c.png)
![image](https://user-images.githubusercontent.com/63096846/79997541-01f77700-84ba-11ea-92f3-561bce2a1a5a.png)
La croix rouge pour dire qu'on a loupé un truc te parait évocateur ?

**Jour fini**
![image](https://user-images.githubusercontent.com/63096846/79997778-34a16f80-84ba-11ea-8526-ed07487f034e.png)
![image](https://user-images.githubusercontent.com/63096846/79997803-3a975080-84ba-11ea-862c-ef7b01f53a95.png)
Sinon, la flèche classique avec une barre au bout pour faire le jour me semble bien.

**Comment by Zetrypio** [comment]
Je ne reviens pas sur ceux qui sont déjà cochés.
 - ![image](https://user-images.githubusercontent.com/61354872/79999211-f1e09700-84bb-11ea-8b27-832b997ab88a.png) : c'est bien, mais ça fait trop tiret car il est trop long. Il faut trouver un juste milieu. (Peut-être au 2/3 ?)
 - ![image](https://user-images.githubusercontent.com/61354872/79999418-2ce2ca80-84bc-11ea-8a07-30fa5da50fb4.png) : manque le contour, mais sinon validé.
 - ![image](https://user-images.githubusercontent.com/61354872/79999589-64517700-84bc-11ea-91e2-c5d9723350b2.png) : Pourquoi tu voulais faire 2 version ? D'ailleurs, j'hésite encore entre ce que tu as fait de ma version et celle-ci.
 - ![image](https://user-images.githubusercontent.com/61354872/79999834-b2667a80-84bc-11ea-85c0-054a4cdecf8b.png) : C'est parfait, mais le trait gris en haut fait bizarre quand on parle des heures. Il passe pour le jour, mais fait étrange pour les heures. Soit on fait 2 images, soit on enlève le trait dans les 2 cas, pour faire le même contour tout du long. Validé.
 - ![image](https://user-images.githubusercontent.com/61354872/80000100-ffe2e780-84bc-11ea-9ec3-abcae3039198.png) : remplace la flèche par ![image](https://user-images.githubusercontent.com/61354872/80000310-46384680-84bd-11ea-9150-ad93eeb7deec.png) pour que ce soit plus visible / lisible. De plus, cette image m'évoque plus le "Avancement normal" que le "Jour Fini", car pour le jour fini, j'aurais mis le trait avant la fin de la flèche, un peu comme ça mais en mieux : ![image](https://user-images.githubusercontent.com/61354872/80001191-6288b300-84be-11ea-9731-50e988549800.png) .
 - ![image](https://user-images.githubusercontent.com/61354872/80000412-6831c900-84bd-11ea-9886-7bb062d3f8ca.png) : la croix n'évoque pas correctement le symbole de retard, Le mieux est ce que je viens de voir sur le gestionnaire de planification de tâche d'Eclipse, à savoir : une horloge rouge en retard, qui évoquera bien le retard. (Ce qu'il y a sur Eclipse : ![image](https://user-images.githubusercontent.com/61354872/80001380-949a1500-84be-11ea-9d51-65b82baff8ca.png) - Oui je sais c'est tout petit, mais nous on va le faire plus grand du coup =) . ) .

**Comment by squelletton** [comment]
- Super suggestion pour l'avancement, je prends tout (ma version initiale était avec le trait du bout qui touche mais j'ai changé sans trop avoir de raison^^)
- pour intervertir il n'y a rien pour les heures, enfaite c'est juste le texte qui est resté, mais il est pas censé être là =), alors je vais refaire avec juste un contour carré (peut-être si l'envie m'en prend de faire une deuxième version avec le bandeau aussi entouré) car la fonction est censé juste inversé 2 jours, ça me semble non pertinent de faire avec les heures.
 - tu vois toi aussi tu trouvé que ça fait tiret, je vais voir ce que je peu faire niveau taille (à voir si ça cause une gêne visuelle au niveau taille avec le plus, bref je vois ce que je peux arranger)
 - Pour les 2 images de masquer/afficher : Comment tu sais si tout est affiché ou pas ? 
   - ma réponse est de faire deux images : 
      - Une pour dire que tout est affiché (aucun filtre actif)
      - Une pour dire que toutes les taches ne sont pas visibles (des filtres actifs, la case du bouton serais couleur "active")

Whooo, ça va vite (me parle pas des texture du Big calendrier stp)

**Comment by squelletton** [comment]
Et encode un shooting photo de plus
**Avancement** il y a de tout
![image](https://user-images.githubusercontent.com/63096846/80111023-a394cc00-857f-11ea-8b16-31831fb1194e.png)
![image](https://user-images.githubusercontent.com/63096846/80111051-abed0700-857f-11ea-83b7-52113e79a4fb.png)
Voilà pour les 3 et bien placé en plus =), l'avancement normal comme iil a une grande case, pourquoi pas allonger la flèche ou rajouter un 100% ou un truc du genre à coté, t'en pense quoi, ça passe comme ça ?

**Intervertir**
![image](https://user-images.githubusercontent.com/63096846/80111653-70067180-8580-11ea-9678-0ebb6abade48.png)
![image](https://user-images.githubusercontent.com/63096846/80111670-75fc5280-8580-11ea-8553-b1df23f7d7e6.png)
Voilà, ça me parait pas mal.

**Afficher/masquer**
![image](https://user-images.githubusercontent.com/63096846/80114669-1ef87c80-8584-11ea-8c62-604dd4e57782.png)
![image](https://user-images.githubusercontent.com/63096846/80114693-2586f400-8584-11ea-800a-37885dafb75d.png)
Les "éclats de visions" sont légers mais visibles, qu'est ce que tu en penses ?
La barre en pointillé donne rien, alors j'ai mis la barre.

**Retirer**
2/3 d'avant
![image](https://user-images.githubusercontent.com/63096846/80115294-dee5c980-8584-11ea-99b9-d66cfca90b82.png)
1/3, c'est un peu ridicule, mais c'est drôle alors je le mets
![image](https://user-images.githubusercontent.com/63096846/80115508-19e7fd00-8585-11ea-93c2-368711c22936.png)
2/3 en longueur et normal en hauteur
![image](https://user-images.githubusercontent.com/63096846/80115751-692e2d80-8585-11ea-9047-fd20d8f79492.png)
Il es possible que le dernier s'arrange avec la taille du texte qui va le suivre.
Sinon la croix c'est pas trop grave, c'est comme ça que sur word c'est fait (le texte est supprimer une ligne, on peut dire pareil)

**Décaler de X heures**
![image](https://user-images.githubusercontent.com/63096846/80117825-ed81b000-8587-11ea-9ce2-be43820e2385.png)
![image](https://user-images.githubusercontent.com/63096846/80117852-f6728180-8587-11ea-961c-a75c7d60c0e5.png)
Ça exprime ce que je veux dire ou pas assez ?

**Décaler de X jour**
![image](https://user-images.githubusercontent.com/63096846/80118137-4bae9300-8588-11ea-82da-89b49c35a937.png)
![image](https://user-images.githubusercontent.com/63096846/80118166-52d5a100-8588-11ea-978e-e9319eeb6826.png)
J'ai juste tournée la flèche et le tour est joué

Petit plus cadeau, toutes mes textures font 46x46 à l'exception des flèches qui font 19x46 =)
Yeah, au moins ça de fat (m^me si je vais devoir en retoucher la moitié, ça fait du bien de se dire qu'on a une texture (même mauvaise) pour tous.

**Comment by Zetrypio** [comment]
- **Retirer :** On garde `2/3 en longueur et normal en hauteur`, Parfait, Validé.
 - **Afficher/Masquer :** Parfait, Validé.
 - **Intervertir :** Parfait, Validé.

 - **Déplacer X activités de Y jours :** Pas double flèche, car pour moi ça veut dire "étendre la vue", ou "élargir". Je pense aussi qu'il faudrait plusieurs colonnes, pour bien montrer l'idée de jours. En d'autres termes, je pense à ça (mais en mieux comme d'habitude) : ![image](https://user-images.githubusercontent.com/61354872/80122962-8c110f80-858e-11ea-8d50-e4e0582d2a62.png)
 - **Déplacer X activités de Y Heures :** Idem, Pas doubles flèches. De plus (et c'est aussi le cas pour celui au-dessus), il y a trop de lignes dans la case (je trouve) et on devrait mettre un contour sur celles qui sont "déplacés". La flèche devrait partir de la case, pour aller ailleurs. J'ai une idée similaire pour les heures, mais la flèche va vers le bas, il n'y a qu'une seule colonne. Peut-être si tu as le courage, on pourras faire une flèche courbée (bonne chance si tu te lances là-dedans...).
 - Pour le **retard :** Je cite :
> Retard ouvre une sélection des tache à faire jusqu’à today.now et permet de cocher les quelques taches non faites
Je pense qu'il ne faut pas de flèches. Seulement la petit horloge... (À tester bien entendu)
 - Pour l'**avancement normal :** C'est bien mais il vaudrait mieux prendre la version que j'avais faite (la différence se situe au niveau de la longueur du triangle de la flèche) et je trouve que c'est bien mieux comme j'ai fait, c'est plus lisible.
 - Pour le **Jour Fini :** Idem. Mais il vaudrait mieux que ce soit le **Jour Fini** qui soit dans le bouton du bas, avec le 100% (très bonne idée au passage).

**Comment by squelletton** [comment]
Petit shooting photo
**Retard**
![image](https://user-images.githubusercontent.com/63096846/80137312-5fb3be00-85a3-11ea-897a-5eab00ec7efc.png)
![image](https://user-images.githubusercontent.com/63096846/80137326-66423580-85a3-11ea-9a29-8508cef36035.png)
Je sais pas ce que tu en pense, mais je trouve pas trop évocateur de retard, si tu trouve que oui je vais soumettre la texture à un juge suprême @Maliochka le type qui veut pas faire les textures

**Comment by squelletton** [comment]
Et encore un shooting photo pour la forme
**Décalage heure**
 - Flèche droite
![image](https://user-images.githubusercontent.com/63096846/80218892-0e0e4080-8642-11ea-935d-931e1b650f9e.png)
![image](https://user-images.githubusercontent.com/63096846/80217722-778d4f80-8640-11ea-968e-a0b5d618ff94.png)
- Flèche courbe
![image](https://user-images.githubusercontent.com/63096846/80218672-c687b480-8641-11ea-9c00-f773cdc6aa88.png)
![image](https://user-images.githubusercontent.com/63096846/80218694-cbe4ff00-8641-11ea-9d38-d8ff20ae5aab.png)

Rien que parce que j'ai fais une flèche __courbe__ je le préfère =)

**Décalage jour**
![image](https://user-images.githubusercontent.com/63096846/80220227-cf798580-8643-11ea-9318-f7e9f7e9aa89.png)
![image](https://user-images.githubusercontent.com/63096846/80220252-d607fd00-8643-11ea-8dc5-b32bcba7a451.png)
voilà ce que ça donne, sur ton image test, tu avais fait un bandeau gris en haut mais d'un gris plus claire, j'ai gardé le même gris sombre moi, ça te vas ?

**Comment by squelletton** [comment]
![image](https://user-images.githubusercontent.com/63096846/80235991-be883e80-865a-11ea-83bf-b30b65139e4b.png)

**Comment by squelletton** [comment]
**Groupe**
![image](https://user-images.githubusercontent.com/63096846/80242744-21cb9e00-8666-11ea-9335-863cae3a2e7b.png)
