### ISSUE TITLE
Les liens ne réapparaissent pas 2 fois

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#87]
Quand on crée un lien entre 2 taches de n'importe quel type (inconnu ou fixe)

Lorsqu'on ferme et redemarre l'application, ça fonctionne correctement.
Seulement à l'enregistrement les taches n'ont plus ni dépendances, ni dépendantes.
Donc si on relance après il n'y a plus de lien.

Alors que si on relance avec la méthodes `Application#restart()` il n'y a aucun soucis

**Comment by squelletton** [comment]
J'ai réussi à déterminer qu'avant que la méthode `Application#save()`soit appelé, les dépendances sont vide.
Je n'arrive pas à déterminer à quel moment elle se vident.

**Comment by Zetrypio** [comment]
On pourrait mettre un affichage de traceback dès que les liens changent... avec les properties par exemple
