### ISSUE TITLE
La selection jour ne fonctionne plus

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#88]
bon tout est dans le titre (Calendrier classique et gantt)
Ni la couleur (tache et barre de jour)
Alors que les schedulables semblent réagir aux fonctions

**Comment by Zetrypio** [comment]
Alors en fait c'est quand il y a des groupes vides. Voir #89

**Comment by squelletton** [comment]
En effet
Quand je corrigerais les groupes pour ne plus avoir de groupes vide, je fermerais cette issue au passage.
