### ISSUE TITLE
Delete les groupes sans taches

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#89]
Faire en sorte de supprimer un groupe s'il n'a plus de tache

Ça implique de revoir (avec simplification) :
 - [x] Dégrouper
 - [ ] askEditGroupe

**Comment by Zetrypio** [comment]
Alors pour dégrouper, c'est déjà fait.

**Comment by squelletton** [comment]
justement avec simplification, si on met le delete dans le removeTask, il n'y a plus qu'a simplifier ça
