### ISSUE TITLE
Édition des répétitions

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#91]
Mettre des méthodes pour changer les répétition/ faire une tache répétable

De plus, l'implémenter dans TaskParametre et adapter le champs car il en manque un, Il faut : 
 - [x] nombre de répétition
 - [x] nombre de l'intervalle
 - [x] unité de l'intervalle

**Comment by squelletton** [comment]
L'attribut était là, mais il manquant de l'afficher.
Reste plus qu'a faire une méthode pour set les répétions d'une tache

**Comment by Zetrypio** [comment]
On peut éditer le nombre de répétitions, mais pas encore le temps entre 2 répétitions. je vais essayer de le faire en tout cas en partie.
