### ISSUE TITLE
Les liens ne se mettent pas à jour

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#92]
Image 1 ![image](https://user-images.githubusercontent.com/63096846/90563902-c0938180-e1a4-11ea-9381-adf139447382.png)
Image 2 ![image](https://user-images.githubusercontent.com/63096846/90563949-d43ee800-e1a4-11ea-8cfd-194cbfe4d62e.png) 
Image 3 ![image](https://user-images.githubusercontent.com/63096846/90564047-fe90a580-e1a4-11ea-9438-8ea929729f28.png)
Image 4 ![image](https://user-images.githubusercontent.com/63096846/90564362-9098ae00-e1a5-11ea-93f6-40d98a4b40ed.png) 

Si on change la durée ou que l'on décale un jour le lien ne suit pas la tache/ le lien de la task de plusieurs jour ne s'actualise pas.
Pour l'image 4, j'ai fait un lien entre deux taches et la tache du début, je l'ai déplacé jusqu'a après la tache de fin

**Comment by Zetrypio** [comment]
J'ai comme l'impression qu'il faut forcer l'updateAffichage (je veux dire, mettre True au paramètre de cette méthode) pour gantt, quand on fait les actions qui amènent à cela.
