### ISSUE TITLE
Bug d'affichage sur les taches hors plage horaire le matin

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#97]
![image](https://user-images.githubusercontent.com/63096846/90987154-214a0200-e589-11ea-95ee-50ac9d0cedf7.png)
### Comment reproduire :
 - Créer une tache qui ne se trouve pas dans la plage horaire du calendrierClassique sur le matin

On voit que la tache est "par dessus" la tache verte aussi
En Drag and drop autant qu'en tache normal

**Comment by Zetrypio** [comment]
D'après ce que je vois, la tâche se fini à 3h du matin, donc normalement on ne devrait pas la voir du tout.
Peux-tu me confirmer ?

**Comment by squelletton** [comment]
Oui c'est ça, d'ailleurs c'est la même chose avec les groupes
